In [ ]:
# Import the necessary modules
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,r2_score,root_mean_squared_error
from sklearn.linear_model import LinearRegression

In [ ]:
df = pd.read_csv("Housing_data.csv",
                 parse_dates=['date'])
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   datetime64[ns]
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64
 8   view           4600 non-null   int64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4600 non-null   int64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   object
 15  city           4600 non-null   object
 16  statezip       4600 non-null   object
 17  country        4600 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(9), object(4)
memory usage: 647.0+ KB

In [ ]:
df['street'].value_counts()

street
2520 Mulberry Walk NE    4
2500 Mulberry Walk NE    3
2803 SW Bataan St        2
8354 11th Ave NW         2
6008 8th Ave NE          2
                        ..
25919 SE 37th Way        1
14435 SE 263rd St        1
2150 N 128th St          1
2043 NE 98th St          1
18923 SE 416th St        1
Name: count, Length: 4525, dtype: int64

In [ ]:
df.shape

(4600, 18)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.shape

(4600, 18)

In [ ]:
df.drop(columns=['country'], inplace=True)

In [ ]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip
0,2014-05-02,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133
1,2014-05-02,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119
2,2014-05-02,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042
3,2014-05-02,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008
4,2014-05-02,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052

In [ ]:
df['statezip']=df['statezip'].apply(lambda x: int(x.replace('WA ','')))

In [ ]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip
0,2014-05-02,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,98133
1,2014-05-02,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,98119
2,2014-05-02,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,98042
3,2014-05-02,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,98008
4,2014-05-02,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,98052

In [ ]:
df['statezip'].value_counts()

statezip
98103    148
98052    135
98117    132
98115    130
98006    110
        ...
98047      6
98288      3
98050      2
98354      2
98068      1
Name: count, Length: 77, dtype: int64

In [ ]:
stnol=[]
stname = []
for i in df['street']:
  x=i.split(' ')
  if not x[0].isnumeric():
    x[0]=x[0].replace('-','')
    print(x[0])
    if x[0].isnumeric():
      stnol.append(int(x[0]))
      stname.append(' '.join(x[1:]))
    else:
      stnol.append(0)
      stname.append(' '.join(x))
  else:
    stnol.append(int(x[0]))
    stname.append(' '.join(x[1:]))

2620626214
4661146625
BurkeGilman
38384098
84368438
72017399
51725198
48014899
59446082
205206
3000130021
2272122727
2092720999
92889358
90209024
2302423198
3200032072
3160731633
232nd
62536299
1280912907
44214564
33013389
1500715299
47034707
2700027080
52005298
2746927501
9202A
29733563
1451314521
2980529821
629899
East
46094699
206458
400498
1873018798
20842104
2163021648
3170131799
108150
92459249
Cedar
44364446
1146111577
10471099
Indian
1969319799
2244222446
80828160
512598
3640036452
16001608
40304198
61016149
17071713
1708117183
81268196
475547
60006048
1650116515
1480014822
1140011598
65206588
14581462
2102321029
1890118937
1370413712
86008698
45274553
1960119853
15011515
16171621
2720027218
62276299
921927
48004898
2970129727
1491714999
1820018298
1711017116
2980129829
49414949
801921
2491124917
84428514
60176199
25002556
1860018698
96129618
79137935
3164931799
56015605
65216599
1620016398
80418299
1940019498
11061128
126th
2357123613
1128311399
86018633
2961329615
1400714017
15001598
1951619598
1450014526
66056609
89309034
9245a
1501715023
1958419766
34383474
Trossachs
24412499
1421614228
36013733
1710117103
66016699
64026412
ShangriLa
24962598
2020620212
57005798
1929619336
48014999
3274032998
19491953
46004748
2752327527
Valley
20002098
25232533
18401846
45014507
2991029918
53075311
Schmitz
2743327475
1503515041
30211/2
3295532977
23172399
1534615348
1590115999
31003198
SE
1442614598
1203512225
54215499
60576061
14041418
61946470
Indian
1671816726
1203212038
1553015998
2280122899
18551899
70757131
1651816526
36003698
1690117007
54045410
63116399
2160121799
1372613736
17181748
25652599
1600016098
50505132
47924798
2580425810
1050010598
53345394
24112499
3380033998
21542398
86008604
92019231
14741476
57005798
3360133799
3333633412
719
2630026398
48114815
1580015898
98019999
3250032514
38173821
10091225
92259305
9751005
1430214314
2745627498
1140011616
SE
1027B
1297512983
1980719813
11491199
80448112
40294035
1002510037
1420014230
50115021
1810718199
77497999
61326198
3712437118
1286912951
Eastridge
Sunrise
2420124231
74467498
1602116299
554598
1781217818
1453214536
79017911
1082210830
1415014198
63016399
3084130959
2792427998
Evergreen
1920C
1100111025
30363040
74077411
3490135199
2600026198
38213825
62776399
27213279
45174529
3184531899
56415645
74227426
11011199
2250022614
70757131
1020010216
2612026126
96259701
3064030650
1134111399
472598
214220
42014213
1844718509
1925919499
50015099
3214832298
2111421120
1850018560
1212012198
2480124805
2170021712
3242832598
3530135323
2492024925
65206588
1820118223
213th
67376741
2420424298
89068914
52945296
133rd
1126311611
2420024498
20002098
14301920
1084310857
1990119999
425445
278th
83018399
101115
1021/2
53215327
18191827
1406B
1430114399
Tolt
24012499
1060010650
2763127699
24012599
Bennett
2110121199
12011215
76577801
3324733248
28002998
335345
33233325
932968
769821
1809618162
Nuthatch
21012499
26012667
29002998
29002948
44244438
2712527131
26th
41494399
30633103
59015909
1162611630
Adair
3160531625
16001718
1200012098
BurkeGilman
1250012578
2458824638
1729517403
1000010026
1122A
2082420836
Brooktrails
25012507
3270132911
978816090
1231412426
16411699
2330023306
3264833020
4360043610
65046618
3160031726
36093615
2130121399
1086711003
701711
2592125929
1911719123
1900919021
34013599
1873818798
1490114999
12231237
28022804
26012649
1958519799
1420114211
1421914231
11491199
1012010198
3003630116
1162011698
13011303
101127
1812418204
110112
15171519
1432314347
3040130499
4304B
32273399

In [ ]:
stnol

[18810,
 709,
 2620626214,
 857,
 9105,
 522,
 2616,
 23762,
 4661146625,
 6811,
 0,
 38384098,
 1833,
 2504,
 3534,
 14034,
 15424,
 11224,
 1605,
 12425,
 3225,
 3922,
 3140,
 10212,
 2021,
 27736,
 84368438,
 1036,
 23525,
 3314,
 14104,
 20120,
 72017399,
 17052,
 51725198,
 30822,
 48014899,
 23017,
 17825,
 3628,
 4460,
 2019,
 121,
 4458,
 7542,
 15804,
 26069,
 4314,
 2640,
 15712,
 26429,
 3923,
 6222,
 32418,
 19334,
 4071,
 36850,
 7425,
 3400,
 59446082,
 35229,
 13800,
 9927,
 29734,
 5608,
 8053,
 13256,
 7528,
 13134,
 13420,
 925,
 151,
 205206,
 22314,
 13615,
 1411,
 120,
 23140,
 12645,
 3187,
 18915,
 1765,
 8624,
 24502,
 14319,
 2120,
 209,
 10512,
 9126,
 20220,
 11821,
 13026,
 125,
 2171,
 3434,
 5211,
 3503,
 114,
 8536,
 3930,
 17132,
 10204,
 218,
 12621,
 14013,
 34010,
 2506,
 8814,
 4515,
 4924,
 4312,
 22912,
 27106,
 13129,
 1014,
 14150,
 2601,
 12807,
 4529,
 1804,
 1701,
 8681,
 26408,
 17717,
 8040,
 901,
 519,
 14017,
 3000130021,
 16026,
 2272122727,
 18027,
 2092720999,
 1857,
 353,
 18427,
 2803,
 13313,
 4532,
 92889358,
 4509,
 1318,
 12001,
 842,
 14359,
 935,
 7809,
 2027,
 792,
 1273,
 17122,
 10601,
 412,
 11051,
 18114,
 25305,
 6422,
 310,
 9712,
 90209024,
 1629,
 2755,
 2815,
 6009,
 3922,
 5631,
 14876,
 8652,
 18305,
 1415,
 19007,
 17435,
 2302423198,
 3200032072,
 17253,
 8409,
 25434,
 18048,
 15007,
 5424,
 207,
 100,
 11853,
 12633,
 15607,
 7422,
 1708,
 33945,
 16020,
 24507,
 32827,
 415,
 2214,
 2560,
 12525,
 920,
 9041,
 16022,
 24201,
 13714,
 22344,
 5650,
 17649,
 3250,
 21603,
 4711,
 14707,
 3160731633,
 12116,
 15418,
 1703,
 3230,
 7434,
 5215,
 4206,
 30020,
 720,
 8300,
 31966,
 2112,
 2516,
 1003,
 135,
 3665,
 7000,
 710,
 8846,
 1435,
 16775,
 1749,
 105,
 5628,
 1028,
 25823,
 25502,
 9626,
 21326,
 14613,
 19313,
 2806,
 25339,
 8809,
 10627,
 16635,
 19654,
 5003,
 4,
 3845,
 32223,
 15204,
 624,
 29645,
 1230,
 1713,
 33331,
 9703,
 234,
 4140,
 206,
 5531,
 232,
 11105,
 18611,
 25525,
 331,
 4602,
 3723,
 12921,
 0,
 62536299,
 1718,
 1225,
 1280912907,
 9724,
 6708,
 1902,
 1234,
 32631,
 44214564,
 1200,
 4313,
 1761,
 33013389,
 19501,
 903,
 3529,
 20821,
 11907,
 18227,
 5902,
 138,
 1500715299,
 18911,
 5146,
 3827,
 47034707,
 1010,
 517,
 733,
 32016,
 2700027080,
 8514,
 19302,
 2145,
 605,
 25408,
 3235,
 13248,
 11304,
 11017,
 10908,
 3631,
 31898,
 7956,
 12303,
 513,
 2814,
 27930,
 7401,
 30633,
 544,
 1825,
 52005298,
 3612,
 434,
 1669,
 235,
 12207,
 8448,
 624,
 23733,
 24345,
 14816,
 2746927501,
 4022,
 28123,
 15020,
 17622,
 2509,
 7304,
 11921,
 8230,
 12612,
 3002,
 13711,
 18748,
 1914,
 14317,
 468,
 4305,
 1816,
 1031,
 5933,
 13221,
 5524,
 3220,
 806,
 2561,
 13812,
 9842,
 1012,
 8013,
 13611,
 1237,
 12227,
 17128,
 365,
 10621,
 2121,
 32817,
 17109,
 168,
 15451,
 8565,
 0,
 36521,
 15917,
 322,
 4714,
 4924,
 744,
 29733563,
 4010,
 1417,
 2113,
 7630,
 743,
 2050,
 19505,
 1451314521,
 2411,
 19490,
 7021,
 31714,
 15407,
 2980529821,
 19707,
 3005,
 33134,
 629899,
 3809,
 4205,
 12727,
 2211,
 0,
 10614,
 46094699,
 206458,
 6255,
 7418,
 14320,
 13532,
 17814,
 9507,
 13615,
 3331,
 32704,
 24345,
 13905,
 4127,
 429,
 23801,
 15217,
 401,
 1614,
 3319,
 18616,
 21423,
 9828,
 2655,
 9921,
 3026,
 3502,
 1211,
 400498,
 439,
 1873018798,
 16828,
 7701,
 21612,
 445,
 11110,
 26621,
 20842104,
 2163021648,
 29606,
 3170131799,
 819,
 29612,
 33030,
 21227,
 108150,
 8608,
 9610,
 15610,
 1721,
 11131,
 2653,
 19226,
 10312,
 92459249,
 33001,
 7070,
 820,
 10834,
 0,
 6521,
 9908,
 5940,
 906,
 5411,
 25005,
 3503,
 2500,
 9155,
 106,
 17050,
 9413,
 3603,
 19211,
 3709,
 3017,
 1216,
 44364446,
 31907,
 4430,
 16512,
 9214,
 2346,
 5537,
 21709,
 7953,
 5220,
 16411,
 215,
 20325,
 2420,
 17217,
 5145,
 11725,
 1614,
 1733,
 1146111577,
 10471099,
 11618,
 8223,
 9202,
 26405,
 5900,
 30928,
 23549,
 4410,
 20248,
 24127,
 570,
 11521,
 414,
 13222,
 0,
 29621,
 9319,
 8107,
 124,
 124,
 731,
 9640,
 2455,
 13730,
 9311,
 1969319799,
 16580,
 16251,
 618,
 950,
 8434,
 23014,
 3219,
 10442,
 5650,
 1716,
 7815,
 10774,
 2244222446,
 1313,
 18416,
 80828160,
 512598,
 2476,
 18125,
 2065,
 15801,
 2831,
 23726,
 19293,
 4018,
 25523,
 7349,
 18913,
 2448,
 1020,
 8028,
 7408,
 10412,
 4958,
 9045,
 1405,
 27020,
 420,
 3640036452,
 16001608,
 18307,
 16700,
 5461,
 171,
 4812,
 718,
 1673,
 14700,
 27747,
 10711,
 19615,
 4437,
 7325,
 40304198,
 12446,
 12033,
 13540,
 4115,
 14710,
 3883,
 11409,
 4902,
 8421,
 18015,
 324,
 2830,
 61016149,
 17071713,
 2301,
 1708117183,
 2711,
 15018,
 16541,
 81268196,
 16014,
 217,
 2278,
 6206,
 16722,
 4118,
 4222,
 9250,
 29140,
 15846,
 14405,
 7741,
 3616,
 7125,
 7617,
 12467,
 213,
 9314,
 7921,
 615,
 5138,
 6544,
 10037,
 353,
 7730,
 3446,
 3810,
 1109,
 7558,
 921,
 28511,
 14319,
 721,
 404,
 475547,
 26205,
 200,
 11549,
 4607,
 60006048,
 4254,
 8622,
 2901,
 2500,
 18527,
 6917,
 316,
 21560,
 2145,
 13547,
 2363,
 15905,
 322,
 11909,
 14836,
 7557,
 1650116515,
 8715,
 1522,
 1807,
 5242,
 27204,
 1456,
 33610,
 920,
 1400,
 1480014822,
 30004,
 14937,
 14923,
 3305,
 14235,
 2000,
 2033,
 14244,
 1140011598,
 504,
 26021,
 1909,
 3755,
 16824,
 10872,
 13622,
 3047,
 16,
 65206588,
 6133,
 24217,
 10441,
 2559,
 15924,
 26054,
 5491,
 4620,
 12901,
 36023,
 7590,
 4036,
 808,
 14581462,
 4531,
 833,
 24231,
 12902,
 12713,
 16231,
 12208,
 2102321029,
 12145,
 1001,
 4137,
 19415,
 1422,
 3539,
 29611,
 11515,
 5212,
 18218,
 14013,
 4446,
 4531,
 5419,
 1323,
 8121,
 17013,
 11401,
 15839,
 3311,
 4216,
 13219,
 5038,
 1106,
 2548,
 309,
 26118,
 29031,
 24038,
 392,
 2145,
 11738,
 26516,
 7822,
 1922,
 18949,
 1315,
 35219,
 17228,
 12415,
 1890118937,
 1370413712,
 4103,
 7558,
 1610,
 2609,
 601,
 86008698,
 3825,
 26635,
 4020,
 10320,
 10904,
 2816,
 12033,
 4530,
 45274553,
 12215,
 17620,
 2419,
 170,
 4417,
 19107,
 12331,
 1960119853,
 9881,
 5021,
 31215,
 25707,
 8024,
 13105,
 12711,
 6849,
 6516,
 8124,
 4042,
 16703,
 2561,
 10835,
 1746,
 401,
 11123,
 44402,
 13012,
 15011515,
 1778,
 28507,
 23013,
 12054,
 26010,
 14040,
 12652,
 2610,
 11931,
 16171621,
 24246,
 4111,
 27022,
 1512,
 2559,
 12040,
 2720027218,
 16221,
 20721,
 36415,
 17849,
 2207,
 22610,
 5255,
 8627,
 3419,
 3200,
 6504,
 1001,
 2001,
 22119,
 120,
 9930,
 26004,
 9055,
 411,
 26607,
 2504,
 24925,
 15421,
 7752,
 18819,
 4080,
 2012,
 35019,
 21481,
 6510,
 62276299,
 373,
 17510,
 4468,
 921927,
 2204,
 18303,
 419,
 14117,
 13440,
 7426,
 8023,
 2049,
 2906,
 800,
 22020,
 7008,
 833,
 4625,
 12611,
 48004898,
 27305,
 6411,
 15511,
 5151,
 7353,
 8024,
 44633,
 5612,
 7341,
 7615,
 8309,
 11428,
 365,
 2970129727,
 44250,
 10635,
 30271,
 615,
 11807,
 15024,
 2500,
 7360,
 24023,
 11053,
 17822,
 6211,
 1714,
 26715,
 821,
 2023,
 6305,
 4621,
 18581,
 10510,
 816,
 1820,
 240,
 18524,
 14926,
 10805,
 454,
 3646,
 16215,
 1491714999,
 6728,
 1755,
 16336,
 901,
 10010,
 6729,
 23911,
 1820018298,
 4751,
 1711017116,
 23902,
 2632,
 714,
 20402,
 13322,
 2313,
 8354,
 4,
 2009,
 9445,
 12418,
 12449,
 1806,
 2980129829,
 34115,
 2913,
 7928,
 2019,
 17428,
 915,
 13342,
 4810,
 4844,
 14223,
 12516,
 3522,
 12206,
 8040,
 7032,
 13615,
 2422,
 16822,
 16819,
 49414949,
 9237,
 1427,
 2612,
 3429,
 5028,
 801921,
 6046,
 3720,
 9226,
 2019,
 1715,
 21533,
 5830,
 13424,
 2525,
 1505,
 14634,
 16864,
 24729,
 602,
 6428,
 7358,
 1106,
 24957,
 1833,
 20515,
 3014,
 1178,
 556,
 5501,
 12840,
 4017,
 2602,
 2212,
 2139,
 10830,
 7757,
 425,
 17814,
 21922,
 32819,
 11332,
 2625,
 20013,
 16420,
 7529,
 701,
 ...]

In [ ]:
stname

['Densmore Ave N',
 'W Blaine St',
 '143rd Ave SE',
 '170th Pl NE',
 '170th Ave NE',
 'NE 88th St',
 '174th Ave NE',
 'SE 253rd Pl',
 'SE 129th St',
 '55th Ave NE',
 'BurkeGilman Trail',
 '44th Ave NE',
 '220th Pl NE',
 'SW Portland Ct',
 '46th Ave NE',
 'SE 201st St',
 'SE 9th St',
 'SE 306th Pl',
 'S 245th Pl',
 '415th Ave SE',
 'NE 92nd St',
 '154th Ave SE',
 'Franklin Ave E',
 'NE 156th Pl',
 'NE 100th St',
 '23rd Avenue South',
 '41st Ave SW',
 '4th St',
 'SE 32nd Way',
 'NW 75th St',
 '119th Ave NE',
 '137th Ave NE',
 '55th Ave NE',
 '4th Ave NE',
 'Heather Ave SE',
 '36th Ct SW',
 '6th Ave NW',
 'SE 281st Ct',
 '4th Ave SW',
 '59th Ave SW',
 '332nd Ave SE',
 'Aberdeen Pl SE',
 'NE 147th St',
 '51st Ave SW',
 '21st Ave SW',
 '198th Pl NE',
 'SE 154th St',
 'NE 6th Pl',
 'NW 56th St',
 'NE 136th Pl',
 'SE 154th Pl',
 '229th Pl SE',
 '30th Ave NE',
 'NE 50th St',
 '89th Ave NE',
 '156th Ave SE',
 '204th Ave SE',
 'Snowberry Ave SE',
 '21st Ave W',
 'Delridge Way SW',
 'SE Terrace St',
 '453rd Ave SE',
 '174th Ave SE',
 '215th Terrace SE',
 'NE 5th Cir',
 '29th Ave NW',
 '242nd Pl SE',
 'N Fork Rd SE',
 '234th Ct NE',
 'SE 182nd St',
 '48th Ct',
 'Euclid Ave',
 'Euclid Ave',
 'NE 11th Pl',
 'NE 100th St',
 'N 48th St',
 '31st Ave E',
 'NE 14th Ct',
 'SE 27th St',
 'NE Larkspur Ln',
 'SE 42nd Pl',
 '267th Ct SE',
 'Island Dr S',
 'SE Mirrormont Dr',
 '85th Pl NE',
 'NE 168th St',
 '30th Ave E',
 '128th Ave NE',
 '45th Ave SW',
 '8th Ave S',
 'NE 48th Pl',
 '10th Ave NW',
 '29th Ave',
 'Boyer Ave E',
 '33rd Ave W',
 '116th Pl SE',
 'NE 44th St',
 'SW 292nd St',
 'Interlake Ave N',
 'NE Belvoir Pl',
 'SE 100th St',
 '168th Pl NE',
 '109th Ave SE',
 'SE 300th Way',
 'Ashworth Ave N',
 'SE Sorenson St',
 '166th Ave NE',
 '218th Ave NE',
 'SW Trenton St',
 'SW 314th Pl',
 'Woodlawn Ave N',
 'SE 268th Pl',
 'NE Miller St',
 '195th Pl SE',
 'W Garfield St',
 '75th Ave NE',
 '21st Ave S',
 '7th Ave S',
 '135th Ave SE',
 'E Beaver Lake Dr SE',
 'N 204th Pl',
 'Beacon Ave S',
 'NE 70th St',
 '113th Pl SE',
 '39th Ave NE',
 'N 97th St',
 'N 104th St',
 'Roslyn Pl N',
 '55th Pl S',
 'SE 137th Terrace',
 'SE 27th St',
 'SE 128th St',
 '2nd Ave S',
 '41st Ave E',
 'NW 88th St',
 'NE 26th Way',
 'NE 62nd St',
 '127th Pl NE',
 '185th Ave SE',
 'Holman Rd NW',
 '185th Ave SE',
 '29th Ave S',
 '173rd Pl NE',
 'Summerhill Ridge Dr NW',
 '19th Ave NE',
 '4th Ave NE',
 '12th Ave NE',
 'Ferndale Ave NE',
 'Summerhill Ridge Dr NW',
 'NE Hickory Ln',
 'NE 117th St',
 'NE 138th Pl',
 'NW 70th St',
 '35th Ave NE',
 'NE 136th St',
 '151st Pl SE',
 'Marshall Ave SW',
 'NW 72nd St',
 '4th Ave NW',
 '11th Ave NW',
 'S 261st Pl',
 'NW Pine Cone Dr',
 'SW 107th St',
 '52nd Ave NE',
 'SW Henderson St',
 '17th Ave SW',
 'Juanita Woodinville Way NE',
 '17th Ave SW',
 'Dayton Ave N',
 '168th Ave NE',
 '80th Ave NE',
 'SE 47th St',
 '17th Ave S',
 'NE 55th St',
 'Ambaum Blvd S',
 'NE 129th Pl',
 '160th Ave SE',
 '3rd Ave NW',
 '75th Ave NE',
 'NE 10th St',
 'NW 5th St',
 '24th Ave E',
 'SE 176th Ct',
 'NE 133rd Pl',
 'SE 42nd Ct',
 'NE 163rd St',
 'NW 96th St',
 '28th Pl SW',
 'SE 2nd St',
 'NE 77th Pl',
 '22nd Ave SW',
 'NE 94th St',
 'W Halladay St',
 '39th Ave W',
 '458th Ave SE',
 '221st Ave NE',
 'NE 160th Pl',
 'SE 43rd St',
 'SE 1st Pl',
 'Ashworth Ave N',
 'NE 31st St',
 'NE 55th St',
 'NE 129th Pl',
 '165th Ave SE',
 'NE 29th St',
 'University View Pl NE',
 'SE 84th St',
 '44th Ave S',
 'SE 71st Pl',
 '216th Ave NE',
 'NW 200th Ln',
 'NE 95th St',
 'Winona Ave N',
 '32nd Ave S',
 'SE Newport Way',
 '43rd Pl S',
 'N 80th St',
 'SE 82nd St',
 '36th Ave SW',
 'N 50th St',
 'Yale Ave E',
 'SW 307th St',
 '25th Ave E',
 'Renton Ave S',
 '23rd Ave NW',
 'S 23rd St',
 'Midvale Ave N',
 '104th Ave SE',
 'NE 86th Ct',
 'NW 60th St',
 'SW 129th St',
 'NE 59th St',
 'NE 153rd Ct',
 'NE 30th Ct',
 'Kanasket Dr',
 'NE 129th Pl',
 'SE 277th Pl',
 '6th Ave SW',
 '140th Pl SE',
 '13th Ave W',
 'SE 248th St',
 'Densmore Ave N',
 'NE 45th St',
 'SE 268th St',
 '116th Ave SE',
 '159th Ct NE',
 '128th Ave SE',
 'Whitman Ave N',
 'NE 88th St',
 '88th Ave NE',
 'SW 137th St',
 '10th Pl S',
 'Warren Ave N',
 '22nd Ave S',
 'NE Lake Joy Rd',
 '130th Ave NE',
 'W Lake Sammamish Pkwy SE',
 '53rd Ave SW',
 'Oakesdale Ave SW',
 'Seward Park Ave S',
 'SW 154th St',
 '126th Ave NE',
 'SE 307th Ln',
 'SE 133rd St',
 '22nd Ave E',
 'Woodlawn Ave N',
 'S Chicago St',
 '79th Pl NE',
 '232nd Way',
 '15th Ave NE',
 'N 175th St',
 'N 41st Pl',
 '206th Ave NE',
 'NE 14th St',
 '14th Ave NW',
 '45th Ave SW',
 '22nd Ave E',
 '39th Ave SW',
 '186th Ave SE',
 'N 27th Pl',
 'SW Willow St',
 '17th Ave S',
 '289th Ave NE',
 '135th Ave SE',
 '22nd Ave E',
 'W Howe St',
 'SE 135th St',
 'SE 261st Pl',
 'SE 135th St',
 '37th Ave SW',
 'Seattle Blvd S',
 '37th Ave NE',
 'NE 165th Pl',
 'S 303rd Pl',
 '39th Ave S',
 '4th Ave NE',
 'NW Inneswood Dr',
 '32nd Ave S',
 '1st Ave N',
 '8th Ave S',
 '201st Ave SE',
 'S 124th St',
 '65th Pl NE',
 'Condon Way W',
 'N 178th St',
 'Lake Wilderness Country Club Dr SE',
 '30th Ave W',
 'Occidental Ave S',
 'Corliss Ave N',
 '101st Pl NE',
 '101st Pl NE',
 'Greenwood Ave N',
 '50th Pl S',
 '46th Ave S',
 'Sand Point Way NE',
 'N 46th St',
 '13th Ave W',
 'NE 147th Pl',
 '92nd Pl SE',
 '21st Ave SW',
 'NE 84th St',
 '251st Pl SE',
 '90th Ave SE',
 'Interlake Ave N',
 'Pullman Ave',
 '28th Ave NE',
 'Thelma St',
 'NE 139th Pl',
 'Delridge Way SW',
 'Lake Washington Blvd E',
 'NE Salal Pl',
 '35th Pl S',
 'SE 278th St',
 'SE 154th Pl',
 'SW Walker St',
 '123rd Pl SE',
 'SE 281st St',
 '12th Ave SW',
 '33rd Ave S',
 '217th Pl NE',
 'SE 205th St',
 'Corliss Ave N',
 '23rd Ave S',
 '109th Ave SE',
 'SE 251 Pl',
 'SE 330th St',
 'S 375th St',
 '22nd Ave NE',
 'Scenic Way',
 'S Webster St',
 '26th Ave',
 '272nd Pl SE',
 'S Eastwood Dr',
 '3rd Ave NW',
 '161st Pl NE',
 '170th Ave NE',
 '15th Ave E',
 '3rd Ave W',
 '196th Ave NE',
 'Vineyard Crest',
 'N 42nd Pl',
 '20th Ave NE',
 'Bear Creek Rd NE',
 'S Sullivan St',
 '47th Ave S',
 'NE 92nd St',
 'Halladay St',
 'NE 107th Pl',
 '46th Ave SW',
 '10th Pl SW',
 '139th Pl SE',
 'S 192nd Pl',
 '22nd Ave SW',
 'E Mercer Way',
 '9202A Interlake Ave N',
 'SE 94th St',
 'NE 109th Way',
 '9th Ave N',
 'Thackeray Pl NE',
 'SE 2nd Pl',
 'N 83rd St',
 'SW 172nd St',
 'Linden Ave N',
 '4th Ave W',
 '15th Ave S',
 'Todd Pl',
 'N 71st St',
 '14th Ave W',
 'NE 143rd St',
 '164th Pl SE',
 'Meadow Ave N',
 'SE 57th Pl',
 '24th Ave NW',
 '125th Pl SE',
 'SE 252nd Pl',
 '129th Pl SW',
 'NE 181st St',
 '211th Ave NE',
 '3rd Ct SW',
 'Cedar Ave S',
 '260th Ave SE',
 'NE 169th Ct',
 '2nd Ave SW',
 '20th Ave S',
 'East Lake Sammamish Trail',
 '57th Ave S',
 'Preston-Fall City Rd SE',
 'Lingering Pine Dr NW',
 '4th Ave NW',
 'Dogwood Ln SE',
 '84th Ave NE',
 '15th Pl NE',
 '161st Ave SE',
 'Ashworth Ave N',
 'Somerset Ln SE',
 'S 368th Pl',
 '33rd Ave SW',
 '35th Pl S',
 '184th Ave NE',
 'Fauntleroy Way SW',
 'Milwaukee Blvd S',
 'SE 162nd St',
 '80th Ave NE',
 '31st Ave E',
 '32nd Ave',
 'S 262nd St',
 '215th Way NE',
 '114th Pl SE',
 '159th Pl NE',
 '166th Ave SE',
 '227th Way NE',
 'S Star Lake Rd',
 'Morris Ave S',
 'NE 135th St',
 '211th Pl NE',
 'SW 156th St',
 '109 Ln SE',
 '166th Pl SE',
 '16th Ave NW',
 'SE 290th Ct',
 'Meadow Dr SE',
 'NE 38th Pl',
 'SE 22nd Way',
 '144th Ave SE',
 'NE 67th St',
 'SE 286 St',
 'SE 291st St',
 'NE 125th St',
 '2nd Ave SW',
 'NE 201st St',
 'SE 278th Way',
 'Union Ave SE',
 'N Mercer Way',
 '8th Ave NE',
 'NE 159th St',
 'NE 98th St',
 'SE 183rd Pl',
 '46th Ave SW',
 '76th Pl NE',
 'Linden Ave N',
 'Fremont Ave N',
 'NE 24th St',
 '270th Pl SE',
 'NW 95th St',
 '31st Ave SW',
 'Cedar to Green River Trail',
 'Fremont Ave N',
 'S 210th Pl',
 'California Ave SW',
 '17th Ave',
 'Fauntleroy Way SW',
 'NE Patterson Way',
 'NE 43rd St',
 'Mulberry Walk NE',
 'NE 21st Pl',
 '24th Ave E',
 '14th Avenue Northeast',
 '34th Ave SW',
 'W Mercer Way',
 'SE 342nd St',
 '131st Ave NE',
 'SW Hinds St',
 '86th Ave NE',
 'W Mercer Way',
 'NE 139th St',
 'Letitia Ave S',
 'SE 64th Pl',
 'Cyrus Ave NW',
 'N 59th St',
 'S 119th St',
 'SE 255th Pl',
 '14th Ave SW',
 'SW Pritchard St',
 '120th Ave SE',
 '243rd Ave SE',
 'NE 198th St',
 'Dogwood St SE',
 'Woodside Dr SE',
 'S Roxbury St',
 'NE 102nd Pl',
 '33rd Ave',
 'NE 88th St',
 '172nd Ave NE',
 'S 130th St',
 'NE 65th St',
 'SE 71st St',
 'SE 46th St',
 '218th Ave SE',
 '20th Ave NW',
 '148th Ave SE',
 'NE 111th St',
 'Burke Ave N',
 '20th Ave NE',
 'SE 45th Pl',
 'Wilderness Peak Dr NW',
 '22nd Ave NE',
 '14th Ave',
 'NE 193rd Pl',
 'Indian Trail',
 '18th Ave S',
 '45th Ave SW',
 '165th Ave NE',
 'SW 185th St',
 'NE 61st St',
 'McGilvra Blvd E',
 'NE 32nd St',
 'Queen Anne Ave N',
 '2nd Ave NW',
 'NE 142nd St',
 'SE Maple Valley Hwy',
 'SE 57th Pl',
 '12th Ave SW',
 'NW 49th St',
 'NW 60th St',
 'W Mercer Way',
 'Vashon Hwy SW',
 '34th Ave W',
 'SE 13th St',
 'Fauntleroy Way SW',
 'California Ave SW',
 'Stroud Ave N',
 '155th Pl NE',
 'Southeast 281st Court',
 '4th St',
 '172nd Ct SE',
 '142nd Ave NE',
 '21st Ave',
 '239th Pl NE',
 '194th Ave NE',
 'NE Nelson Ln',
 '63rd Ave NE',
 'SW 327th St',
 'NE 134th Pl',
 'Stone Ave N',
 'NE 6th Ct',
 '123rd Pl SE',
 '24th Ave NW',
 'SE 63rd Pl',
 '137th Ave SE',
 '163rd Ave SE',
 '27th Ave NE',
 '138th Pl NE',
 'Aqua Way S',
 '12th Ave S',
 'NE 40th Pl',
 'E Maple St',
 'NE Ring St',
 'Boylston Ave E',
 '51st Ave S',
 '25th Ave',
 'NE 19th Pl',
 'SE 161st St',
 'S Othello St',
 'Lake Washington Blvd',
 'S Chicago St',
 'N 95th St',
 'Rosemont Blvd',
 'Burke Ave N',
 'SE 24th Way',
 'SW 111th Pl',
 '182nd Ave NE',
 '55th Ave NE',
 'Earl Ave NW',
 'S 186th St',
 '21st Ave S',
 'NE 136th Pl',
 'Burke Ave N',
 'SW 106th St',
 '122nd Pl NE',
 '112th Ave NE',
 'SE 71st Pl',
 '159th Pl SE',
 'SE 72nd Pl',
 '25th Ave NE',
 'NW 48th St',
 '177th Ave NE',
 'Corliss Ave N',
 '3rd Ave N',
 'California Ave SW',
 'SE Wax Rd',
 '126th Ave SE',
 'NE 10th Pl',
 'NE 27th Pl',
 'Forest Ave SE',
 '16th Ave SW',
 'SW 191st St',
 '72nd Ave SE',
 'Phinney Ave N',
 '32nd Pl NE',
 '32nd Ave SW',
 'S 288th Pl',
 'SE 36th Pl',
 '42nd Ave S',
 '196th Pl NE',
 '274th Ct NE',
 '22nd Ave NE',
 'NE 65th St',
 'Silent Creek Ave SE',
 'NE 201st Pl',
 'NE 171st Pl',
 '26th Ave E',
 'Ash Ave SE',
 '45th Ave SW',
 'NW 92nd St',
 'NE 8th St',
 '18th Ave SW',
 'Interlake Ave N',
 'N 105th St',
 '33rd Ave NW',
 '77th Ave SE',
 '145th Ave SE',
 '32nd Ave',
 '32nd Ave NW',
 'S 223rd St',
 '10th Ave S',
 '165th Pl SE',
 '222nd Pl NE',
 'SW 197th St',
 'Monroe Ave NE',
 '119th Dr SE',
 'Pike St SE',
 'SE 319th Pl',
 'SW Cloverdale St',
 '22nd Ave S',
 '33rd Ave W',
 'NE 139th St',
 'W Elmore St',
 'Mulberry Walk NE',
 'Kenlake Pl NE',
 '28th Ave NW',
 'Lake Washington Blvd S',
 'SE 275th Ct',
 'N 88th St',
 'SE 83rd St',
 '30th Ave NE',
 'Saybrook Dr NE',
 '16th Ave',
 'SE 228th Pl',
 'Densmore Ave N',
 '35th Ave NE',
 'Carlyle Hall Rd N',
 '17th Ave NW',
 '55th Ct SE',
 '17th Ave S',
 '336th Ave SE',
 '116th Pl SE',
 'NW 185th St',
 '51st Ave S',
 '163rd Ave SE',
 'S 359th St',
 '88th Ave NE',
 'SE Lake Retreat S Dr',
 '57th Ave S',
 '280th Pl NE',
 '39th Ave W',
 '160th Ave NE',
 'NE 113th St',
 '211th Pl SE',
 '140th Ave SE',
 'SE 114th Pl',
 'Shelton Ct NE',
 'NE 25th St',
 'N 195th St',
 'S 168th St',
 '11th Pl NE',
 'SE 318th Pl',
 'NE 136th Pl',
 '21st Ave W',
 'R Pl NE',
 '8th Ave NW',
 '147th Pl NE',
 '181st Pl SE',
 'SE 24th Pl',
 'NE 98th St',
 'NE 53rd St',
 'SE 23rd Pl',
 '175th Pl SE',
 'Kennedy Ave SE',
 'NE 136th St',
 '3rd Ave S',
 '86th Ave SE',
 'S 119th St',
 'Hoquiam Ave NE',
 '29th Pl NE',
 '205th Pl NE',
 'SW 361st St',
 'NE 5th Pl',
 'SE 158th Pl',
 'SE 302nd St',
 'NE 29th St',
 '20th Ave S',
 'NE 42nd St',
 'SE 260th Pl',
 'Whitman Ct NE',
 '48th Ave SW',
 '107th Ave SE',
 'S 282nd Pl',
 'NW 67th St',
 '21st Ave S',
 '4th Ave NE',
 'Wallingford Ave N',
 'Evanston Ave N',
 '101st Pl NE',
 'S 160th St',
 'S Lucile St',
 '156th Ave NE',
 '145th Ave SE',
 'NE 147th Pl',
 'NE 133rd St',
 'SE 219th Pl',
 '84th Ave NE',
 'SE 17th St',
 '232nd Ave NE',
 '424th Ave SE',
 '48th Ave NE',
 '25th Ave E',
 '111th Ave SE',
 'N 46th St',
 'SE 39th Ct',
 '40th Ave S',
 'SE 13th Pl',
 'Wilderness Peak Dr NW',
 'N 178th St',
 '1st Ave NE',
 '235th Ave SE',
 'NE 14th St',
 '35th Ave W',
 'Mountain View Rd NE',
 '232nd Pl NE',
 '26th Ct S',
 '11th Ave NE',
 'NE 160th St',
 '114th Ct SE',
 '209th Ave NE',
 'SW Kenyon St',
 '19th Ave SW',
 'N 185th St',
 '21st Ave S',
 'NE 76th St',
 '30th Ave NE',
 '138th Ave SE',
 'Timberlane Dr SE',
 '21st Ave SW',
 'NE 125th Pl',
 'SE 1st St',
 'SW 110th Pl',
 'Dayton Ave N',
 '48th Ave SW',
 'NE 201st Pl',
 'Dayton Ave N',
 'SE 121st Pl',
 'SW Barton St',
 'Mt Quay Dr NW',
 '47th Ave S',
 'NE 64th Way',
 'A 10th Pl NE',
 'Newport Way NW',
 '244th Pl NE',
 'Delridge Way SW',
 'SE 40th St',
 'SE 30th St',
 '117th Pl SE',
 'SE 277th Pl',
 '470th Ave SE',
 '26th Ave NE',
 'Denny Peak Dr SE',
 '24th Ave SW',
 '34th Ave SW',
 '133rd Pl SE',
 'NE 85th St',
 '41st Ave SW',
 'NW 60th St',
 'SW 322nd St',
 'NE 141st Pl',
 'SE 142nd Pl',
 '41st Ave S',
 'SW 327th St',
 '26th Ave NE',
 'Vashon Hwy SW',
 'NE 28th St',
 'NE 137th Ct',
 '141st Ave SE',
 '24th Ave NE',
 'SE 160th St',
 'E Montlake Pl E',
 '179th Pl NE',
 '3rd Ave W',
 '229th Ave SE',
 'Woodland Park Ave N',
 '216th Ave SE',
 'NW 62nd St',
 '24th Ave W',
 '201st Pl NE',
 '52nd Ave S',
 'Bagley Pl N',
 '9th Ave S',
 '12th Pl S',
 '149th Ave NE',
 'Kennewick Pl NE',
 '133rd Pl SE',
 '39th Ave NE',
 '9th Ave SW',
 'SW Morgan St',
 '44th Ave SW',
 'E Crest View Loop SE',
 'SW 102nd St',
 'S Norman St',
 '123rd Ave SE',
 'Mt Si Pl NW',
 'NE 197th St',
 '18th Ave S',
 'Palatine Ave N',
 '27th Ave E',
 '190th Ave SE',
 '225th Pl NE',
 '234th Pl SE',
 'SE 4th Pl',
 '33rd Ave NW',
 '71st Ave NE',
 'E Mercer Way',
 'NW Boulder Way Dr',
 'SE Terrace St',
 'SE 2nd Pl',
 '34th Ave SW',
 'Whitaker Ln SE',
 'NE Eagle Way',
 '12th Ave NE',
 '158th Ave SE',
 '18th Ave',
 'W Emerson St',
 '155th Pl SE',
 'Wetherbee Ln',
 '175th Ave NE',
 'NE 148th St',
 'N Fork Rd SE',
 '12th Ave NE',
 '144th Ave SE',
 'Kennewick Pl NE',
 'NE 95th St',
 '127th Ct SE',
 '19th Ave NW',
 'SW 346th St',
 'Somerset Dr SE',
 'SE 160th St',
 'Whitman Ave N',
 '245th Ave SE',
 '22nd Ave NW',
 '9th Ave NE',
 'S Othello St',
 '16th Ave NW',
 'S 130th St',
 'SE 151st St',
 '18th Ave SW',
 '20th Ave NE',
 'SW 257th St',
 '36th Ave S',
 'SE 225th St',
 'Crockett St',
 '138th Ave SE',
 'SE Edgewick Rd',
 'SE 2nd St',
 '129th Ave SE',
 'NW 92nd St',
 'NE 105th Ct',
 'Wallingford Ave N',
 'Mulberry Walk NE',
 '19th Ave NW',
 'SE 282nd St',
 'Greenwood Ave N',
 'NE 154th St',
 'Ravenna Ave NE',
 'SW 354th Pl',
 'Stanford Ct',
 'Dayton Ave NE',
 '24th Ave S',
 '150th Ave NE',
 '193rd Pl SE',
 '134th Pl NE',
 '160th Ave NE',
 'NW Market St',
 '24th Ave',
 'S 198th St',
 'SE 60th St',
 'NE 202nd St',
 '177th Ct NE',
 'A St',
 'Dayton Ave N',
 'SE 172nd Ct',
 '27th Pl S',
 '40th Ave SW',
 '140th Ct SE',
 '131st Ave SE',
 '18th Ave',
 '44th Ave SW',
 '37th Ave S',
 'SE 6th St',
 '13th Ave NW',
 'Stephens Ave',
 '146th Ave SE',
 '6th Ave S',
 'NW North Beach Dr',
 'NE 10th St',
 '63rd Ave NE',
 'SE 77th Ct',
 'NW 65th St',
 '11th Ave NW',
 '151st Pl NE',
 '4th Ave N',
 '8th Ave SW',
 'NE 100th St',
 '240th Pl NE',
 '11th Ave',
 '23rd Avenue South',
 'SE Ash St',
 '278th Ave SE',
 'NE 182nd Pl',
 '24th Ave S',
 '7th Pl SW',
 '6th Ave N',
 '30th Ave NE',
 'S Raymond St',
 '47th Ave SW',
 'SE 179th Pl',
 'Military Rd S',
 'SW 107th St',
 'SE 217th St',
 'S 118th St',
 '7th Ave NW',
 '179th Ave NE',
 'E McGraw St',
 'NE 87th St',
 'SE 171st Pl',
 '125th Ave SE',
 '7th Ave NW',
 'NW 62nd St',
 '49th Ave SW',
 '9th Ave W',
 '157th Ave SE',
 'Martin Luther King Jr Way S',
 '126th Ave NE',
 'S 312th Ln',
 'S 239th Pl',
 '182nd Ave NE',
 '46th Ave SW',
 'NE Woodinville Duvall Rd',
 '246th Pl NE',
 'NE 80th St',
 'NE 24th St',
 '29th Ave',
 '128th Ave NE',
 'SE 57th Pl',
 'SE 276th Pl',
 'Tacoma Ave NE',
 'NE 184th St',
 '28th Ave SW',
 'N 80th St',
 'SE 279th St',
 '1st Ave N',
 'SE 333rd Pl',
 'NW Esplanade',
 'Camas Ave NE',
 'N 167th St',
 '37th Ave NE',
 '163rd Ave SE',
 '36th Ave SW',
 'Shoreland Dr S',
 'N 36th St',
 'N 52nd St',
 '132nd Ave NE',
 '15th Ave SW',
 'S 305th St',
 'SE 257th St',
 '34th Ave S',
 '17th Ave SW',
 '30th Ave NE',
 '82nd Ave NE',
 '15th Ave NW',
 'SE 39th Pl',
 'Lakemont Dr NE',
 'S 52nd St',
 ...]

In [ ]:
df['streetname']=stname
df['streetno']=stnol

In [ ]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,streetname,streetno
0,2014-05-02,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,98133,Densmore Ave N,18810
1,2014-05-02,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,98119,W Blaine St,709
2,2014-05-02,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,98042,143rd Ave SE,2620626214
3,2014-05-02,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,98008,170th Pl NE,857
4,2014-05-02,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,98052,170th Ave NE,9105

In [ ]:
df['streetno'].value_counts()

streetno
0        35
2500      5
720       5
2520      5
124       5
         ..
9719      1
530       1
2611      1
3218      1
27831     1
Name: count, Length: 3838, dtype: int64

In [ ]:
df['streetname'].value_counts()

streetname
41st Ave SW       11
35th Ave SW       11
Ashworth Ave N    11
33rd Ave S        11
37th Ave SW       11
                  ..
SE 78th St         1
165th Pl NE        1
SE 187th Pl        1
46th Ave NE        1
SE 201st St        1
Name: count, Length: 2617, dtype: int64

In [ ]:
le = LabelEncoder()
df[['streetname','city']]=df[['streetname','city']].apply(le.fit_transform)

In [ ]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,streetname,streetno
0,2014-05-02,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,36,98133,1078,18810
1,2014-05-02,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,35,98119,2558,709
2,2014-05-02,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,18,98042,184,2620626214
3,2014-05-02,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,3,98008,297,857
4,2014-05-02,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,31,98052,294,9105

In [ ]:
df['date'].value_counts()

date
2014-06-23    142
2014-06-25    131
2014-06-26    131
2014-07-08    127
2014-07-09    121
             ...
2014-06-07      4
2014-07-06      3
2014-05-11      2
2014-07-04      2
2014-05-17      1
Name: count, Length: 70, dtype: int64

In [ ]:
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df['weekday'] = df['date'].dt.weekday
df['weekno'] = df['date'].dt.isocalendar().week

In [ ]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,street,city,statezip,streetname,streetno,year,month,day,weekday,weekno
0,2014-05-02,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,...,18810 Densmore Ave N,36,98133,1078,18810,2014,5,2,4,18
1,2014-05-02,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,...,709 W Blaine St,35,98119,2558,709,2014,5,2,4,18
2,2014-05-02,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,...,26206-26214 143rd Ave SE,18,98042,184,2620626214,2014,5,2,4,18
3,2014-05-02,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,...,857 170th Pl NE,3,98008,297,857,2014,5,2,4,18
4,2014-05-02,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,...,9105 170th Ave NE,31,98052,294,9105,2014,5,2,4,18

In [ ]:
df['month'].value_counts()

month
6    2179
5    1768
7     653
Name: count, dtype: int64

In [ ]:
df.drop(['date','year','street'],axis=1,inplace= True)

In [ ]:
df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,...,yr_built,yr_renovated,city,statezip,streetname,streetno,month,day,weekday,weekno
0,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,...,1955,2005,36,98133,1078,18810,5,2,4,18
1,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,...,1921,0,35,98119,2558,709,5,2,4,18
2,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,...,1966,0,18,98042,184,2620626214,5,2,4,18
3,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,...,1963,0,3,98008,297,857,5,2,4,18
4,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,...,1976,1992,31,98052,294,9105,5,2,4,18

In [ ]:
df['yr_built'].value_counts()

yr_built
2006    111
2005    104
2007     93
2004     92
1978     90
       ...
1915      6
1935      6
1933      5
1934      4
1936      3
Name: count, Length: 115, dtype: int64

In [ ]:
df['yr_renovated'].value_counts()

yr_renovated
0       2735
2000     170
2003     151
2009     109
2001     109
2005      95
2004      77
2014      72
2006      68
2013      61
1923      57
1994      57
1989      55
2011      54
2012      45
2008      45
1988      43
2002      41
1983      41
1999      41
1998      40
1993      39
1912      33
1992      32
1979      32
2010      30
1985      29
1997      28
1996      22
1982      22
1972      17
1990      16
1956      15
1963      12
1969      11
1984      10
1968       9
1970       9
1954       8
1945       7
2007       7
1974       6
1934       6
1958       5
1986       5
1971       5
1978       3
1955       2
1980       2
1995       2
1981       1
1953       1
1987       1
1966       1
1960       1
1948       1
1991       1
1913       1
1977       1
1975       1
Name: count, dtype: int64

In [ ]:
df.drop(['yr_renovated'],axis=1,inplace=True)

In [ ]:
df['crtage']=df['yr_built'].apply(  lambda x: 2025-x)

In [ ]:
df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,...,yr_built,city,statezip,streetname,streetno,month,day,weekday,weekno,crtage
0,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,...,1955,36,98133,1078,18810,5,2,4,18,70
1,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,...,1921,35,98119,2558,709,5,2,4,18,104
2,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,...,1966,18,98042,184,2620626214,5,2,4,18,59
3,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,...,1963,3,98008,297,857,5,2,4,18,62
4,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,...,1976,31,98052,294,9105,5,2,4,18,49

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   price          4600 non-null   float64
 1   bedrooms       4600 non-null   float64
 2   bathrooms      4600 non-null   float64
 3   sqft_living    4600 non-null   int64
 4   sqft_lot       4600 non-null   int64
 5   floors         4600 non-null   float64
 6   waterfront     4600 non-null   int64
 7   view           4600 non-null   int64
 8   condition      4600 non-null   int64
 9   sqft_above     4600 non-null   int64
 10  sqft_basement  4600 non-null   int64
 11  yr_built       4600 non-null   int64
 12  city           4600 non-null   int64
 13  statezip       4600 non-null   int64
 14  streetname     4600 non-null   int64
 15  streetno       4600 non-null   int64
 16  month          4600 non-null   int32
 17  day            4600 non-null   int32
 18  weekday        4600 non-null   int32
 19  weekno         4600 non-null   UInt32
 20  crtage         4600 non-null   int64
dtypes: UInt32(1), float64(4), int32(3), int64(13)
memory usage: 687.4 KB

In [ ]:
df.describe()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,...,yr_built,city,statezip,streetname,streetno,month,day,weekday,weekno,crtage
count,4.600000e+03,4600.000000,4600.000000,4600.000000,4.600000e+03,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,...,4600.000000,4600.000000,4600.000000,4600.000000,4.600000e+03,4600.000000,4600.000000,4600.000000,4600.0,4600.000000
mean,5.519630e+05,3.400870,2.160815,2139.346957,1.485252e+04,1.512065,0.007174,0.240652,3.451739,1827.265435,...,1970.786304,25.674348,98079.379783,1194.050217,7.514116e+07,5.757609,14.791304,2.005000,23.447174,54.213696
std,5.638347e+05,0.908848,0.783781,963.206916,3.588444e+04,0.538288,0.084404,0.778405,0.677230,862.168977,...,29.731848,11.982721,53.142102,743.658550,4.132881e+08,0.683851,8.677569,1.454154,2.840516,29.731848
min,0.000000e+00,0.000000,0.000000,370.000000,6.380000e+02,1.000000,0.000000,0.000000,1.000000,370.000000,...,1900.000000,0.000000,98001.000000,0.000000,0.000000e+00,5.000000,1.000000,0.000000,18.0,11.000000
25%,3.228750e+05,3.000000,1.750000,1460.000000,5.000750e+03,1.000000,0.000000,0.000000,3.000000,1190.000000,...,1951.000000,17.000000,98033.000000,587.000000,2.806750e+03,5.000000,7.000000,1.000000,21.0,28.000000
50%,4.609435e+05,3.000000,2.250000,1980.000000,7.683000e+03,1.500000,0.000000,0.000000,3.000000,1590.000000,...,1976.000000,32.000000,98072.000000,1099.500000,8.311500e+03,6.000000,14.000000,2.000000,24.0,49.000000
75%,6.549625e+05,4.000000,2.500000,2620.000000,1.100125e+04,2.000000,0.000000,0.000000,4.000000,2300.000000,...,1997.000000,35.000000,98117.000000,1801.000000,1.710525e+04,6.000000,23.000000,3.000000,26.0,74.000000
max,2.659000e+07,9.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,9410.000000,...,2014.000000,43.000000,98354.000000,2616.000000,4.661147e+09,7.000000,31.000000,6.000000,28.0,125.000000

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()
scl = ['sqft_above','sqft_lot','sqft_living','sqft_basement','yr_built','statezip',
       'streetno','streetname']
for i in scl:
  df[i] = pd.DataFrame(sc.fit_transform(df[[i]]))

In [ ]:
df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,...,yr_built,city,statezip,streetname,streetno,month,day,weekday,weekno,crtage
0,313000.0,3.0,1.50,-0.829971,-0.193434,1.5,0,0,3,-0.565224,...,-0.531014,36,1.009107,-0.156070,-0.181787,5,2,4,18,70
1,2384000.0,5.0,2.50,1.568528,-0.161718,2.0,0,4,5,1.789559,...,-1.674693,35,0.745633,1.834307,-0.181831,5,2,4,18,104
2,342000.0,3.0,2.00,-0.217367,-0.080978,1.0,0,0,4,0.119171,...,-0.161000,18,-0.703469,-1.358365,6.159775,5,2,4,18,59
3,420000.0,3.0,2.25,-0.144686,-0.190145,1.0,0,0,4,-0.959621,...,-0.261913,3,-1.343333,-1.206397,-0.181831,5,2,4,18,62
4,550000.0,4.0,2.50,-0.206984,-0.121306,1.0,0,0,4,-0.797222,...,0.175376,31,-0.515274,-1.210432,-0.181811,5,2,4,18,49

In [ ]:
df.drop(['statezip','streetno','streetname'],axis=1,inplace=True)

In [ ]:
y = df.iloc[:,0]
X = df.iloc[:,1:]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.3,
                                                    random_state=42)

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((3220, 17), (1380, 17), (3220,), (1380,))

In [ ]:
reg = LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [ ]:
y_pred = reg.predict(X_test)
print('Mean Absolute Error:', mean_absolute_error(y_test, y_pred))
print('R2 Score:', r2_score(y_test, y_pred))
print('Root Mean Squared Error:', root_mean_squared_error(y_test, y_pred))

Mean Absolute Error: 194625.04379302406
R2 Score: 0.06062091580119433
Root Mean Squared Error: 823805.9740181927

In [ ]:
from sklearn.tree import DecisionTreeRegressor

In [ ]:
reg1=DecisionTreeRegressor(random_state=2021)
reg1.fit(X_train,y_train)

DecisionTreeRegressor(random_state=2021)

In [ ]:
y_pred1 = reg1.predict(X_test)
print('Mean Absolute Error:', mean_absolute_error(y_test, y_pred1))
print('R2 Score:', r2_score(y_test, y_pred1))
print('Root Mean Squared Error:', root_mean_squared_error(y_test, y_pred1))

Mean Absolute Error: 222801.84160661447
R2 Score: -0.044598958866493676
Root Mean Squared Error: 868718.9361391074

In [ ]:
depth_range = [3,4,5,6,7,8,9]
minsplit_range = [5,10,20,25,30]
minleaf_range = [5,10,15]

In [ ]:
parameters = dict(max_depth=depth_range,
                  min_samples_split=minsplit_range,
                  min_samples_leaf=minleaf_range)

In [ ]:
from sklearn.model_selection import KFold
kfold = KFold(n_splits=5, random_state=2021,
                        shuffle=True)

In [ ]:
from sklearn.model_selection import GridSearchCV
clf = DecisionTreeRegressor(random_state=2021)
cv = GridSearchCV(clf, param_grid=parameters,
                  cv=kfold,scoring='r2',verbose=2)

In [ ]:
cv.fit(X_train,y_train)

Fitting 5 folds for each of 105 candidates, totalling 525 fits
[CV] END max_depth=3, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=5, min_samples_split=20; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=5, min_samples_split=20; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=5, min_samples_split=20; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=5, min_samples_split=20; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=5, min_samples_split=20; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=5, min_samples_split=25; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=5, min_samples_split=25; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=5, min_samples_split=25; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=5, min_samples_split=25; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=5, min_samples_split=25; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=5, min_samples_split=30; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=5, min_samples_split=30; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=5, min_samples_split=30; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=5, min_samples_split=30; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=5, min_samples_split=30; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=10, min_samples_split=20; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=10, min_samples_split=20; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=10, min_samples_split=20; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=10, min_samples_split=20; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=10, min_samples_split=20; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=10, min_samples_split=25; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=10, min_samples_split=25; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=10, min_samples_split=25; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=10, min_samples_split=25; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=10, min_samples_split=25; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=10, min_samples_split=30; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=10, min_samples_split=30; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=10, min_samples_split=30; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=10, min_samples_split=30; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=10, min_samples_split=30; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=15, min_samples_split=5; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=15, min_samples_split=5; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=15, min_samples_split=5; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=15, min_samples_split=5; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=15, min_samples_split=5; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=15, min_samples_split=10; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=15, min_samples_split=10; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=15, min_samples_split=10; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=15, min_samples_split=10; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=15, min_samples_split=10; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=15, min_samples_split=20; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=15, min_samples_split=20; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=15, min_samples_split=20; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=15, min_samples_split=20; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=15, min_samples_split=20; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=15, min_samples_split=25; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=15, min_samples_split=25; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=15, min_samples_split=25; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=15, min_samples_split=25; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=15, min_samples_split=25; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=15, min_samples_split=30; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=15, min_samples_split=30; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=15, min_samples_split=30; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=15, min_samples_split=30; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=15, min_samples_split=30; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=5, min_samples_split=20; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=5, min_samples_split=20; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=5, min_samples_split=20; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=5, min_samples_split=20; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=5, min_samples_split=20; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=5, min_samples_split=25; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=5, min_samples_split=25; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=5, min_samples_split=25; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=5, min_samples_split=25; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=5, min_samples_split=25; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=5, min_samples_split=30; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=5, min_samples_split=30; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=5, min_samples_split=30; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=5, min_samples_split=30; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=5, min_samples_split=30; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=10, min_samples_split=20; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=10, min_samples_split=20; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=10, min_samples_split=20; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=10, min_samples_split=20; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=10, min_samples_split=20; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=10, min_samples_split=25; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=10, min_samples_split=25; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=10, min_samples_split=25; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=10, min_samples_split=25; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=10, min_samples_split=25; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=10, min_samples_split=30; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=10, min_samples_split=30; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=10, min_samples_split=30; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=10, min_samples_split=30; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=10, min_samples_split=30; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=15, min_samples_split=5; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=15, min_samples_split=5; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=15, min_samples_split=5; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=15, min_samples_split=5; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=15, min_samples_split=5; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=15, min_samples_split=10; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=15, min_samples_split=10; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=15, min_samples_split=10; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=15, min_samples_split=10; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=15, min_samples_split=10; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=15, min_samples_split=20; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=15, min_samples_split=20; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=15, min_samples_split=20; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=15, min_samples_split=20; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=15, min_samples_split=20; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=15, min_samples_split=25; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=15, min_samples_split=25; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=15, min_samples_split=25; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=15, min_samples_split=25; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=15, min_samples_split=25; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=15, min_samples_split=30; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=15, min_samples_split=30; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=15, min_samples_split=30; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=15, min_samples_split=30; total time=   0.0s
[CV] END max_depth=4, min_samples_leaf=15, min_samples_split=30; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=20; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=20; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=20; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=20; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=20; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=25; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=25; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=25; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=25; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=25; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=30; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=30; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=30; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=30; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=30; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=20; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=20; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=20; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=20; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=20; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=25; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=25; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=25; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=25; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=25; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=30; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=30; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=30; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=30; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=30; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=15, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=15, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=15, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=15, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=15, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=15, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=15, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=15, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=15, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=15, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=15, min_samples_split=20; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=15, min_samples_split=20; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=15, min_samples_split=20; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=15, min_samples_split=20; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=15, min_samples_split=20; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=15, min_samples_split=25; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=15, min_samples_split=25; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=15, min_samples_split=25; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=15, min_samples_split=25; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=15, min_samples_split=25; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=15, min_samples_split=30; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=15, min_samples_split=30; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=15, min_samples_split=30; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=15, min_samples_split=30; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=15, min_samples_split=30; total time=   0.0s
[CV] END max_depth=6, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=6, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=6, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=6, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=6, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=6, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=6, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=6, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=6, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=6, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=6, min_samples_leaf=5, min_samples_split=20; total time=   0.0s
[CV] END max_depth=6, min_samples_leaf=5, min_samples_split=20; total time=   0.0s
[CV] END max_depth=6, min_samples_leaf=5, min_samples_split=20; total time=   0.0s
[CV] END max_depth=6, min_samples_leaf=5, min_samples_split=20; total time=   0.0s

GridSearchCV(cv=KFold(n_splits=5, random_state=2021, shuffle=True),
             estimator=DecisionTreeRegressor(random_state=2021),
             param_grid={'max_depth': [3, 4, 5, 6, 7, 8, 9],
                         'min_samples_leaf': [5, 10, 15],
                         'min_samples_split': [5, 10, 20, 25, 30]},
             scoring='r2', verbose=2)

In [ ]:
results_df = pd.DataFrame(cv.cv_results_  )
results_df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,param_min_samples_leaf,param_min_samples_split,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.012124,0.001339,0.004044,0.000977,3,5,5,"{'max_depth': 3, 'min_samples_leaf': 5, 'min_s...",0.276900,0.388132,0.496988,0.187375,0.546892,0.379257,0.133668,97
1,0.009593,0.000956,0.002982,0.000082,3,5,10,"{'max_depth': 3, 'min_samples_leaf': 5, 'min_s...",0.276900,0.388132,0.496988,0.187375,0.546892,0.379257,0.133668,97
2,0.011003,0.001766,0.003529,0.000560,3,5,20,"{'max_depth': 3, 'min_samples_leaf': 5, 'min_s...",0.376018,0.328911,0.446196,0.187375,0.546892,0.377078,0.119935,101
3,0.009721,0.000345,0.003300,0.000474,3,5,25,"{'max_depth': 3, 'min_samples_leaf': 5, 'min_s...",0.376018,0.328911,0.446196,0.187375,0.504838,0.368668,0.108678,102
4,0.008990,0.000117,0.002814,0.000060,3,5,30,"{'max_depth': 3, 'min_samples_leaf': 5, 'min_s...",0.376018,0.328911,0.446196,0.187375,0.504838,0.368668,0.108678,102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,0.026156,0.004435,0.004136,0.000092,9,15,5,"{'max_depth': 9, 'min_samples_leaf': 15, 'min_...",0.438912,0.367776,0.497621,0.445268,0.519023,0.453720,0.052667,1
101,0.024737,0.000410,0.004528,0.000378,9,15,10,"{'max_depth': 9, 'min_samples_leaf': 15, 'min_...",0.438912,0.367776,0.497621,0.445268,0.519023,0.453720,0.052667,1
102,0.025959,0.000832,0.004840,0.000457,9,15,20,"{'max_depth': 9, 'min_samples_leaf': 15, 'min_...",0.438912,0.367776,0.497621,0.445268,0.519023,0.453720,0.052667,1
103,0.026657,0.002724,0.004940,0.001770,9,15,25,"{'max_depth': 9, 'min_samples_leaf': 15, 'min_...",0.438912,0.367776,0.497621,0.445268,0.519023,0.453720,0.052667,1
104,0.025431,0.000843,0.004309,0.000199,9,15,30,"{'max_depth': 9, 'min_samples_leaf': 15, 'min_...",0.438912,0.367776,0.497621,0.445268,0.519023,0.453720,0.052667,1

In [ ]:
# Best Parameters
print(cv.best_params_)

{'max_depth': 9, 'min_samples_leaf': 15, 'min_samples_split': 5}

In [ ]:
print(cv.best_score_)

0.4537199928959195

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
reg2=RandomForestRegressor(random_state=2021)
reg2.fit(X_train,y_train)

RandomForestRegressor(random_state=2021)

In [ ]:
y_pred2 = reg2.predict(X_test)
print('Mean Absolute Error:', mean_absolute_error(y_test, y_pred2))
print('R2 Score:', r2_score(y_test, y_pred2))
print('Root Mean Squared Error:', root_mean_squared_error(y_test, y_pred2))

Mean Absolute Error: 166151.1108421744
R2 Score: 0.0643571965075509
Root Mean Squared Error: 822166.0412715223

In [ ]:
parameters = dict(max_depth=depth_range,
                  min_samples_split=minsplit_range,
                  min_samples_leaf=minleaf_range,
                  max_features=np.arange(1,11,2))

In [ ]:
reg3=RandomForestRegressor(random_state=2021)
cv1 = GridSearchCV(reg3, param_grid=parameters,
                  cv=kfold,scoring='r2',verbose=2)

In [ ]:
cv1.fit(X_train,y_train)

Fitting 5 folds for each of 525 candidates, totalling 2625 fits
[CV] END max_depth=3, max_features=1, min_samples_leaf=5, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=5, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=5, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=5, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=5, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=5, min_samples_split=10; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=5, min_samples_split=10; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=5, min_samples_split=10; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=5, min_samples_split=10; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=5, min_samples_split=10; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=5, min_samples_split=20; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=5, min_samples_split=20; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=5, min_samples_split=20; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=5, min_samples_split=20; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=5, min_samples_split=20; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=5, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=5, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=5, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=5, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=5, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=5, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=5, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=5, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=5, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=5, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=10, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=10, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=10, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=10, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=10, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=10, min_samples_split=10; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=10, min_samples_split=10; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=10, min_samples_split=10; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=10, min_samples_split=10; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=10, min_samples_split=10; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=10, min_samples_split=20; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=10, min_samples_split=20; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=10, min_samples_split=20; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=10, min_samples_split=20; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=10, min_samples_split=20; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=10, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=10, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=10, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=10, min_samples_split=25; total time=   0.3s
[CV] END max_depth=3, max_features=1, min_samples_leaf=10, min_samples_split=25; total time=   0.3s
[CV] END max_depth=3, max_features=1, min_samples_leaf=10, min_samples_split=30; total time=   0.3s
[CV] END max_depth=3, max_features=1, min_samples_leaf=10, min_samples_split=30; total time=   0.3s
[CV] END max_depth=3, max_features=1, min_samples_leaf=10, min_samples_split=30; total time=   0.3s
[CV] END max_depth=3, max_features=1, min_samples_leaf=10, min_samples_split=30; total time=   0.3s
[CV] END max_depth=3, max_features=1, min_samples_leaf=10, min_samples_split=30; total time=   0.3s
[CV] END max_depth=3, max_features=1, min_samples_leaf=15, min_samples_split=5; total time=   0.3s
[CV] END max_depth=3, max_features=1, min_samples_leaf=15, min_samples_split=5; total time=   0.3s
[CV] END max_depth=3, max_features=1, min_samples_leaf=15, min_samples_split=5; total time=   0.3s
[CV] END max_depth=3, max_features=1, min_samples_leaf=15, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=15, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=15, min_samples_split=10; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=15, min_samples_split=10; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=15, min_samples_split=10; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=15, min_samples_split=10; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=15, min_samples_split=10; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=15, min_samples_split=20; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=15, min_samples_split=20; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=15, min_samples_split=20; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=15, min_samples_split=20; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=15, min_samples_split=20; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=15, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=15, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=15, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=15, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=15, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=15, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=15, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=15, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=15, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=1, min_samples_leaf=15, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=5, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=5, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=5, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=5, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=5, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=5, min_samples_split=10; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=5, min_samples_split=10; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=5, min_samples_split=10; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=5, min_samples_split=10; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=5, min_samples_split=10; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=5, min_samples_split=20; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=5, min_samples_split=20; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=5, min_samples_split=20; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=5, min_samples_split=20; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=5, min_samples_split=20; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=5, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=5, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=5, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=5, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=5, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=5, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=5, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=5, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=5, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=5, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=10, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=10, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=10, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=10, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=10, min_samples_split=5; total time=   0.4s
[CV] END max_depth=3, max_features=3, min_samples_leaf=10, min_samples_split=10; total time=   0.4s
[CV] END max_depth=3, max_features=3, min_samples_leaf=10, min_samples_split=10; total time=   0.3s
[CV] END max_depth=3, max_features=3, min_samples_leaf=10, min_samples_split=10; total time=   0.3s
[CV] END max_depth=3, max_features=3, min_samples_leaf=10, min_samples_split=10; total time=   0.4s
[CV] END max_depth=3, max_features=3, min_samples_leaf=10, min_samples_split=10; total time=   0.3s
[CV] END max_depth=3, max_features=3, min_samples_leaf=10, min_samples_split=20; total time=   0.4s
[CV] END max_depth=3, max_features=3, min_samples_leaf=10, min_samples_split=20; total time=   0.3s
[CV] END max_depth=3, max_features=3, min_samples_leaf=10, min_samples_split=20; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=10, min_samples_split=20; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=10, min_samples_split=20; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=10, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=10, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=10, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=10, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=10, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=10, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=10, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=10, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=10, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=10, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=15, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=15, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=15, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=15, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=15, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=15, min_samples_split=10; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=15, min_samples_split=10; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=15, min_samples_split=10; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=15, min_samples_split=10; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=15, min_samples_split=10; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=15, min_samples_split=20; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=15, min_samples_split=20; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=15, min_samples_split=20; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=15, min_samples_split=20; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=15, min_samples_split=20; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=15, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=15, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=15, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=15, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=15, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=15, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=15, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=15, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=15, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=3, min_samples_leaf=15, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=5, min_samples_leaf=5, min_samples_split=5; total time=   0.3s
[CV] END max_depth=3, max_features=5, min_samples_leaf=5, min_samples_split=5; total time=   0.3s
[CV] END max_depth=3, max_features=5, min_samples_leaf=5, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=5, min_samples_leaf=5, min_samples_split=5; total time=   0.3s
[CV] END max_depth=3, max_features=5, min_samples_leaf=5, min_samples_split=5; total time=   0.3s
[CV] END max_depth=3, max_features=5, min_samples_leaf=5, min_samples_split=10; total time=   0.3s
[CV] END max_depth=3, max_features=5, min_samples_leaf=5, min_samples_split=10; total time=   0.4s
[CV] END max_depth=3, max_features=5, min_samples_leaf=5, min_samples_split=10; total time=   0.4s
[CV] END max_depth=3, max_features=5, min_samples_leaf=5, min_samples_split=10; total time=   0.4s
[CV] END max_depth=3, max_features=5, min_samples_leaf=5, min_samples_split=10; total time=   0.4s
[CV] END max_depth=3, max_features=5, min_samples_leaf=5, min_samples_split=20; total time=   0.4s
[CV] END max_depth=3, max_features=5, min_samples_leaf=5, min_samples_split=20; total time=   0.4s
[CV] END max_depth=3, max_features=5, min_samples_leaf=5, min_samples_split=20; total time=   0.4s
[CV] END max_depth=3, max_features=5, min_samples_leaf=5, min_samples_split=20; total time=   0.3s
[CV] END max_depth=3, max_features=5, min_samples_leaf=5, min_samples_split=20; total time=   0.3s
[CV] END max_depth=3, max_features=5, min_samples_leaf=5, min_samples_split=25; total time=   0.3s
[CV] END max_depth=3, max_features=5, min_samples_leaf=5, min_samples_split=25; total time=   0.3s
[CV] END max_depth=3, max_features=5, min_samples_leaf=5, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=5, min_samples_leaf=5, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=5, min_samples_leaf=5, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=5, min_samples_leaf=5, min_samples_split=30; total time=   0.3s
[CV] END max_depth=3, max_features=5, min_samples_leaf=5, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=5, min_samples_leaf=5, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=5, min_samples_leaf=5, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=5, min_samples_leaf=5, min_samples_split=30; total time=   0.3s
[CV] END max_depth=3, max_features=5, min_samples_leaf=10, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=5, min_samples_leaf=10, min_samples_split=5; total time=   0.2s
[CV] END max_depth=3, max_features=5, min_samples_leaf=10, min_samples_split=5; total time=   0.3s
[CV] END max_depth=3, max_features=5, min_samples_leaf=10, min_samples_split=5; total time=   0.3s
[CV] END max_depth=3, max_features=5, min_samples_leaf=10, min_samples_split=5; total time=   0.3s
[CV] END max_depth=3, max_features=5, min_samples_leaf=10, min_samples_split=10; total time=   0.2s
[CV] END max_depth=3, max_features=5, min_samples_leaf=10, min_samples_split=10; total time=   0.3s
[CV] END max_depth=3, max_features=5, min_samples_leaf=10, min_samples_split=10; total time=   0.3s
[CV] END max_depth=3, max_features=5, min_samples_leaf=10, min_samples_split=10; total time=   0.3s
[CV] END max_depth=3, max_features=5, min_samples_leaf=10, min_samples_split=10; total time=   0.3s
[CV] END max_depth=3, max_features=5, min_samples_leaf=10, min_samples_split=20; total time=   0.3s
[CV] END max_depth=3, max_features=5, min_samples_leaf=10, min_samples_split=20; total time=   0.3s
[CV] END max_depth=3, max_features=5, min_samples_leaf=10, min_samples_split=20; total time=   0.3s
[CV] END max_depth=3, max_features=5, min_samples_leaf=10, min_samples_split=20; total time=   0.3s
[CV] END max_depth=3, max_features=5, min_samples_leaf=10, min_samples_split=20; total time=   0.3s
[CV] END max_depth=3, max_features=5, min_samples_leaf=10, min_samples_split=25; total time=   0.3s
[CV] END max_depth=3, max_features=5, min_samples_leaf=10, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=5, min_samples_leaf=10, min_samples_split=25; total time=   0.2s
[CV] END max_depth=3, max_features=5, min_samples_leaf=10, min_samples_split=25; total time=   0.3s
[CV] END max_depth=3, max_features=5, min_samples_leaf=10, min_samples_split=25; total time=   0.3s
[CV] END max_depth=3, max_features=5, min_samples_leaf=10, min_samples_split=30; total time=   0.2s
[CV] END max_depth=3, max_features=5, min_samples_leaf=10, min_samples_split=30; total time=   0.3s
[CV] END max_depth=3, max_features=5, min_samples_leaf=10, min_samples_split=30; total time=   0.4s
[CV] END max_depth=3, max_features=5, min_samples_leaf=10, min_samples_split=30; total time=   0.3s
[CV] END max_depth=3, max_features=5, min_samples_leaf=10, min_samples_split=30; total time=   0.4s

GridSearchCV(cv=KFold(n_splits=5, random_state=2021, shuffle=True),
             estimator=RandomForestRegressor(random_state=2021),
             param_grid={'max_depth': [3, 4, 5, 6, 7, 8, 9],
                         'max_features': array([1, 3, 5, 7, 9]),
                         'min_samples_leaf': [5, 10, 15],
                         'min_samples_split': [5, 10, 20, 25, 30]},
             scoring='r2', verbose=2)

In [ ]:
results_df = pd.DataFrame(cv1.cv_results_ )
results_df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,param_max_features,param_min_samples_leaf,param_min_samples_split,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.162269,0.006914,0.014142,0.001720,3,1,5,5,"{'max_depth': 3, 'max_features': 1, 'min_sampl...",0.318355,0.280386,0.243593,0.220879,0.295031,0.271649,0.035126,511
1,0.160527,0.007828,0.013093,0.000504,3,1,5,10,"{'max_depth': 3, 'max_features': 1, 'min_sampl...",0.318355,0.280386,0.243593,0.220879,0.295031,0.271649,0.035126,511
2,0.156932,0.004182,0.013864,0.000651,3,1,5,20,"{'max_depth': 3, 'max_features': 1, 'min_sampl...",0.312240,0.273151,0.241027,0.216924,0.287379,0.266144,0.033700,513
3,0.158732,0.006235,0.013714,0.001153,3,1,5,25,"{'max_depth': 3, 'max_features': 1, 'min_sampl...",0.309160,0.272788,0.240806,0.214759,0.286373,0.264777,0.033397,514
4,0.158846,0.006340,0.012762,0.000288,3,1,5,30,"{'max_depth': 3, 'max_features': 1, 'min_sampl...",0.303797,0.272061,0.237975,0.209910,0.287362,0.262221,0.034005,515
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
520,0.639291,0.007168,0.018029,0.001196,9,9,15,5,"{'max_depth': 9, 'max_features': 9, 'min_sampl...",0.539247,0.510957,0.454049,0.470268,0.573685,0.509641,0.043865,67
521,0.795929,0.114069,0.023734,0.005058,9,9,15,10,"{'max_depth': 9, 'max_features': 9, 'min_sampl...",0.539247,0.510957,0.454049,0.470268,0.573685,0.509641,0.043865,67
522,0.639679,0.010405,0.016598,0.000382,9,9,15,20,"{'max_depth': 9, 'max_features': 9, 'min_sampl...",0.539247,0.510957,0.454049,0.470268,0.573685,0.509641,0.043865,67
523,0.640224,0.008579,0.017302,0.000696,9,9,15,25,"{'max_depth': 9, 'max_features': 9, 'min_sampl...",0.539247,0.510957,0.454049,0.470268,0.573685,0.509641,0.043865,67
524,0.697504,0.112531,0.023103,0.005139,9,9,15,30,"{'max_depth': 9, 'max_features': 9, 'min_sampl...",0.539247,0.510957,0.454049,0.470268,0.573685,0.509641,0.043865,67

In [ ]:
# Best Parameters
print(cv1.best_params_)

# Best Score
print(cv1.best_score_)

{'max_depth': 9, 'max_features': np.int64(9), 'min_samples_leaf': 5, 'min_samples_split': 25}
0.5280452898817176